version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce:latest
    networks:
      - traefik-public
      - devops-network

    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro

    environment:
      - BASE_URL=/portainer

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.rule=PathPrefix(`/portainer`)"
        - "traefik.http.routers.portainer.entrypoints=web"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"

volumes:
  portainer_data:

networks:
  traefik-public:
    external: true
  devops-network:
    external: true
