version: "3.9"

services:
  trivy:
    image: aquasec/trivy:latest
    networks:
      - traefik-public
      - devops-network

    command: server --listen 0.0.0.0:8080

    volumes:
      - trivy_cache:/root/.cache/

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

      restart_policy:
        condition: on-failure

      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.trivy.rule=PathPrefix(`/trivy`)"
        - "traefik.http.routers.trivy.entrypoints=web"
        - "traefik.http.services.trivy.loadbalancer.server.port=8080"

volumes:
  trivy_cache:

networks:
  traefik-public:
    external: true
  devops-network:
    external: true
